## Data Encoding

Encoding converts categorical variables into a numerical format that machine learning algorithms can process. This notebook covers:

1. One-Hot Encoding (OHE)
2. Label and Ordinal Encoding
3. Target Guided Ordinal Encoding

---

### One-Hot Encoding (OHE)

One-Hot Encoding creates a new binary column for each unique category. A row gets a  in the column matching its category and  in all others.



Best suited for **nominal** (unordered) categories. Avoid for high-cardinality features, as each unique value adds a new column.

---

### Sparse vs Dense Representation

By default,  returns a **sparse matrix** — only the non-zero values are stored, which is memory-efficient when most entries are zero.

Calling  converts it to a **dense array**, where all values (including zeros) are stored explicitly. Dense arrays are easier to work with but use more memory.

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder

In [2]:
# Create a dataframe
data = {'Color': ['Red', 'Blue', 'Green', 'Red', 'Blue']}
df = pd.DataFrame(data)

In [3]:
df.head()

   Color
0    Red
1   Blue
2  Green
3    Red
4   Blue

In [4]:
# Create an instance of OneHotEncoder
ohe = OneHotEncoder()

In [5]:
# Perform fit and transform the data
encoded_data = ohe.fit_transform(df[['Color']]).toarray()

In [6]:
encoded_data

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [7]:
import pandas as pd
encoder_df = pd.DataFrame(encoded_data, columns=ohe.get_feature_names_out())

In [8]:
encoder_df

   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [13]:
ohe.transform([['Blue']]).toarray()

c:\Users\Sam Ben-Yosef\.conda\envs\feature_engineering\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [14]:
pd.concat([df, encoder_df], axis=1)

   Color  Color_Blue  Color_Green  Color_Red
0    Red         0.0          0.0        1.0
1   Blue         1.0          0.0        0.0
2  Green         0.0          1.0        0.0
3    Red         0.0          0.0        1.0
4   Blue         1.0          0.0        0.0

## Label Encoding

Label encoding assigns each unique category a unique integer. The assignment is alphabetical by default.



**Note:** Label encoding implies an ordinal relationship between categories (0 < 1 < 2), which can mislead models into treating categories as ordered. Use it only for the **target variable** or genuinely binary features — not for nominal input features like color.

In [16]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [17]:
lbl_encoder.fit_transform(df['Color'])

array([2, 0, 1, 2, 0])

In [18]:
lbl_encoder.transform(['Green'])

array([1])

In [19]:
lbl_encoder.transform(['Blue'])

array([0])

## Ordinal Encoding
Ordinal encoding is similar to label encoding, but it takes into account the order of the categories. For example, if we have a variable "Size" with categories "Small", "Medium", and "Large", we could assign "Small" = 0, "Medium" = 1, and "Large" = 2, reflecting the natural order of the sizes.

In [24]:
df = pd.DataFrame({'Size': ['Small', 'Medium', 'Large', 'Medium', 'Small', 'Large', 'Medium', 'Small']})

In [25]:
df

     Size
0   Small
1  Medium
2   Large
3  Medium
4   Small
5   Large
6  Medium
7   Small

In [26]:
# Create an instance of OrdinalEncoder
ord_encoder = OrdinalEncoder(categories=[['Small', 'Medium', 'Large']])

In [27]:
ord_encoder.fit_transform(df[['Size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.]])

In [29]:
ord_encoder.transform([['Medium']])

c:\Users\Sam Ben-Yosef\.conda\envs\feature_engineering\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[1.]])

## Conclusion

Choosing the right encoding strategy depends on whether your feature has a natural order and on the model you are using.

| Method | Use When | Watch Out For |
|---|---|---|
| **One-Hot Encoding** | Nominal data, no natural order | High-cardinality features produce too many columns |
| **Label Encoding** | Target variable or binary features | Implies false ordinal relationships on nominal data |
| **Ordinal Encoding** | Ordered categories (Small < Medium < Large) | Order must be explicitly specified — default is alphabetical |

**Key takeaways:**
- Use OHE for nominal input features with low-to-moderate cardinality
- Use Ordinal Encoding when a meaningful order exists between categories
- Avoid Label Encoding on nominal input features — the implied numeric ordering can introduce bias in linear and distance-based models