## Target Guided Ordinal Encoding

Target Guided Ordinal Encoding (TGOE) is a technique for encoding high-cardinality categorical features by replacing each category with the **mean of the target variable** for that category. Unlike One-Hot Encoding, it adds only one new column regardless of how many unique categories exist, making it well-suited for features with many distinct values.

**How it works:**
1. Compute the mean target value for each category
2. Map each category to its corresponding mean
3. The resulting column carries both the encoding and a signal about the relationship between the category and the target

**Important:** Mean values must be computed on the **training set only**. Computing them on the full dataset leaks target information into the features and will inflate model performance.

In [10]:
import pandas as pd
df = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'New York', 'Chicago', 'New York', 'Houston', 'Phoenix'],
    'price': [250, 150, 300, 250, 320, 280, 200]
})

In [11]:
df

          city  price
0     New York    250
1  Los Angeles    150
2     New York    300
3      Chicago    250
4     New York    320
5      Houston    280
6      Phoenix    200

In [13]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [14]:
mean_price

{'Chicago': 250.0,
 'Houston': 280.0,
 'Los Angeles': 150.0,
 'New York': 290.0,
 'Phoenix': 200.0}

In [15]:
df['city_encoded'] = df['city'].map(mean_price)

In [16]:
df

          city  price  city_encoded
0     New York    250         290.0
1  Los Angeles    150         150.0
2     New York    300         290.0
3      Chicago    250         250.0
4     New York    320         290.0
5      Houston    280         280.0
6      Phoenix    200         200.0

In [18]:
df[['price', 'city_encoded']].drop_duplicates()

   price  city_encoded
0    250         290.0
1    150         150.0
2    300         290.0
3    250         250.0
4    320         290.0
5    280         280.0
6    200         200.0

## Conclusion

Target Guided Ordinal Encoding is a compact, signal-rich alternative to One-Hot Encoding for high-cardinality categorical features.

| | One-Hot Encoding | Ordinal Encoding | Target Guided Ordinal Encoding |
|---|---|---|---|
| New columns added | One per category | 1 | 1 |
| Encodes natural order | No | Yes (if specified) | No |
| Uses target signal | No | No | Yes |
| Risk of data leakage | No | No | Yes (if not careful) |

**When to use TGOE:**
- The categorical feature has many unique values (high cardinality)
- A meaningful relationship exists between the category and the target
- You want to avoid the dimensionality explosion of OHE

**Always fit the encoding on the training set only**, then apply it to the validation and test sets to prevent data leakage.